name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Build with Maven
        run: mvn -B package --file pom.xml
